name: Tests

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies (frontend)
        run: |
          cd dashboard
          npm install

      - name: Run frontend tests
        run: |
          cd dashboard
          npm run test

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.TRACKING_SYSTEM }}

      - name: Install dependencies (backend)
        run: |
          cd new_backend
          npm install

      - name: Run backend tests
        run: |
          cd new_backend
          npm run test

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.TRACKING_SYSTEM }}
